module language_code::language_code;

use std::string::String;

//=== Structs ===

public struct LanguageCode(String) has copy, drop, store;

//=== Errors ===

#[error(code = 0)]
const EInvalidLanguageCode: vector<u8> = b"Invalid language code.";

//=== Public Functions ===

// Creates a new LanguageCode from a string.
public fun new(code: String): LanguageCode {
    assert!(language_codes!().contains(&code), EInvalidLanguageCode);
    LanguageCode(code)
}

//=== Public View Functions ===

// Returns the code field of the LanguageCode.
public fun code(language_code: &LanguageCode): String {
    language_code.0
}

//=== Private Functions ===

// Returns a vector of all the supported language codes in the ISO 639-1 standard.
macro fun language_codes(): vector<String> {
    vector[
        b"aa".to_string(),
        b"ab".to_string(),
        b"ae".to_string(),
        b"af".to_string(),
        b"ak".to_string(),
        b"am".to_string(),
        b"an".to_string(),
        b"ar".to_string(),
        b"as".to_string(),
        b"av".to_string(),
        b"ay".to_string(),
        b"az".to_string(),
        b"ba".to_string(),
        b"be".to_string(),
        b"bg".to_string(),
        b"bh".to_string(),
        b"bi".to_string(),
        b"bm".to_string(),
        b"bn".to_string(),
        b"bo".to_string(),
        b"br".to_string(),
        b"bs".to_string(),
        b"ca".to_string(),
        b"ce".to_string(),
        b"ch".to_string(),
        b"co".to_string(),
        b"cr".to_string(),
        b"cs".to_string(),
        b"cu".to_string(),
        b"cv".to_string(),
        b"cy".to_string(),
        b"da".to_string(),
        b"de".to_string(),
        b"dv".to_string(),
        b"dz".to_string(),
        b"ee".to_string(),
        b"el".to_string(),
        b"en".to_string(),
        b"eo".to_string(),
        b"es".to_string(),
        b"et".to_string(),
        b"eu".to_string(),
        b"fa".to_string(),
        b"ff".to_string(),
        b"fi".to_string(),
        b"fj".to_string(),
        b"fo".to_string(),
        b"fr".to_string(),
        b"fy".to_string(),
        b"ga".to_string(),
        b"gd".to_string(),
        b"gl".to_string(),
        b"gn".to_string(),
        b"gu".to_string(),
        b"gv".to_string(),
        b"ha".to_string(),
        b"he".to_string(),
        b"hi".to_string(),
        b"ho".to_string(),
        b"hr".to_string(),
        b"ht".to_string(),
        b"hu".to_string(),
        b"hy".to_string(),
        b"hz".to_string(),
        b"ia".to_string(),
        b"id".to_string(),
        b"ie".to_string(),
        b"ig".to_string(),
        b"ii".to_string(),
        b"ik".to_string(),
        b"io".to_string(),
        b"is".to_string(),
        b"it".to_string(),
        b"iu".to_string(),
        b"ja".to_string(),
        b"jv".to_string(),
        b"ka".to_string(),
        b"kg".to_string(),
        b"ki".to_string(),
        b"kj".to_string(),
        b"kk".to_string(),
        b"kl".to_string(),
        b"km".to_string(),
        b"kn".to_string(),
        b"ko".to_string(),
        b"kr".to_string(),
        b"ks".to_string(),
        b"ku".to_string(),
        b"kv".to_string(),
        b"kw".to_string(),
        b"ky".to_string(),
        b"la".to_string(),
        b"lb".to_string(),
        b"lg".to_string(),
        b"li".to_string(),
        b"ln".to_string(),
        b"lo".to_string(),
        b"lt".to_string(),
        b"lu".to_string(),
        b"lv".to_string(),
        b"mg".to_string(),
        b"mh".to_string(),
        b"mi".to_string(),
        b"mk".to_string(),
        b"ml".to_string(),
        b"mn".to_string(),
        b"mr".to_string(),
        b"ms".to_string(),
        b"mt".to_string(),
        b"my".to_string(),
        b"na".to_string(),
        b"nb".to_string(),
        b"nd".to_string(),
        b"ne".to_string(),
        b"ng".to_string(),
        b"nl".to_string(),
        b"nn".to_string(),
        b"no".to_string(),
        b"nr".to_string(),
        b"nv".to_string(),
        b"ny".to_string(),
        b"oc".to_string(),
        b"oj".to_string(),
        b"om".to_string(),
        b"or".to_string(),
        b"os".to_string(),
        b"pa".to_string(),
        b"pi".to_string(),
        b"pl".to_string(),
        b"ps".to_string(),
        b"pt".to_string(),
        b"qu".to_string(),
        b"rm".to_string(),
        b"rn".to_string(),
        b"ro".to_string(),
        b"ru".to_string(),
        b"rw".to_string(),
        b"sa".to_string(),
        b"sc".to_string(),
        b"sd".to_string(),
        b"se".to_string(),
        b"sg".to_string(),
        b"si".to_string(),
        b"sk".to_string(),
        b"sl".to_string(),
        b"sm".to_string(),
        b"sn".to_string(),
        b"so".to_string(),
        b"sq".to_string(),
        b"sr".to_string(),
        b"ss".to_string(),
        b"st".to_string(),
        b"su".to_string(),
        b"sv".to_string(),
        b"sw".to_string(),
        b"ta".to_string(),
        b"te".to_string(),
        b"tg".to_string(),
        b"th".to_string(),
        b"ti".to_string(),
        b"tk".to_string(),
        b"tl".to_string(),
        b"tn".to_string(),
        b"to".to_string(),
        b"tr".to_string(),
        b"ts".to_string(),
        b"tt".to_string(),
        b"tw".to_string(),
        b"ty".to_string(),
        b"ug".to_string(),
        b"uk".to_string(),
        b"ur".to_string(),
        b"uz".to_string(),
        b"ve".to_string(),
        b"vi".to_string(),
        b"vo".to_string(),
        b"wa".to_string(),
        b"wo".to_string(),
        b"xh".to_string(),
        b"yi".to_string(),
        b"yo".to_string(),
        b"za".to_string(),
        b"zh".to_string(),
        b"zu".to_string(),
    ]
}
